#!/bin/sh

num=0
fail=""
for file in $1.in
do
    num=$((num+1));
    i=${file%%.in}

    ../debug -b $i.in > 1.tmp
    ../debug -B $i.in > 2.tmp
    diff --side-by-side 1.tmp 2.tmp > $i.tree
    rm 1.tmp 2.tmp

    ../debug -g $i.in > $i.1.s
    if [ "$?" -eq "0" ]
    then
        gcc -m32 $i.1.s -o a 2> $i.1.res
        if [ -e a ]
        then
            ./a > $i.1.res 2> $i.1.res
            rm a
        fi
    else
        cp $i.1.s $i.1.res
    fi

    ../debug -G $i.in > $i.2.s
    if [ "$?" -eq "0" ]
    then
        gcc -m32 $i.2.s -o a 2> $i.2.res
        if [ -e a ]
        then
            ./a > $i.2.res 2> $i.2.res
            rm a
        fi
    else
        cp $i.2.s $i.2.res
    fi

    tmp=$(diff -q -b $i.1.res $i.2.res)
    tmp="$tmp$(diff -q -b $i.out $i.2.res)"

    if [ -z $1 ] && [ "$1" != "n" ]; then echo "$i: $tmp"; fi
    if [ -n "$tmp" ]; then fail="$fail $i"; fi
done
echo "Number of tests: $num"
if [ -z  "$fail" ]
then
    echo "Ok";
else
    echo "Failed: $fail"
fi
